detector: coco
dataset_train: data/arxiv.llama32_3b.train.jsonl
dataset_val: null
sample_k_train: null
sample_k_val: null
model1: roberta-base
output_dir: models/runs_coco
seed: 42
epochs: 6
train_batch_size: 16
eval_batch_size: 64
lr: 2e-5
weight_decay: 0.01
warmup_ratio: 0.06
grad_accum_steps: 1
max_length: 512
fp16: true
train_kwargs:
  max_nodes_num: 150
  with_relation: 2
  gcn_layers: 2
  lambda_cl: 0.1
  cl_temp: 0.07
