detector: coco
data: data/qwen3_4b_2507.example_human.test.jsonl
model1: null
tokenizer: null
# ckpt_base: null
# lora_dir: null
batch_size: 8
threshold: 0.5
seed: 114514
sample_k: 2000
device: 'cuda:0'
max_length: 512
fp16: false
out: 'runs/coco'
save_curves: true
no_progress: false
k_runs: 1
attack_dataset: null
