detector: detective
data: data/arxiv.qwen3_4b.test.jsonl
train_dataset: data/arxiv.llama32_3b.train.jsonl
embedding_model_name: princeton-nlp/unsup-simcse-roberta-base
embedding_ckpt_path: runs_detective_YYYYMMDD-HHMMSS/detector/best/model_best.pth
pooling: average
max_K: 5
knn_backend: torch
cache_root: ~/.cache/mgt_eval
index_name: null
reuse_database: true
save_database: true
use_gpu_index: true
index_batch_size: 8
detective_eval: true
batch_size: 8
threshold: 0.5
seed: 114514
sample_k: 2000
max_length: 512
fp16: true
device: 'cuda:0'
num_workers: 0
out: 'runs/detective'
save_curves: true
no_progress: false
k_runs: 1
