detector: likelihood
data: data/arxiv.qwen3_4b.test.jsonl
model1: EleutherAI/gpt-neo-125m
batch_size: 8
threshold: 0.5
seed: 114514
sample_k: 2000
device: 'cuda:0'
bf16: true
out: 'runs/<detector>'
save_curves: true
no_progress: false
k_runs: 1
detector_kwargs:
  # score_model: EleutherAI/gpt-neo-125m
  # fp16: true
  use_analytic: true
  max_length: 512
  calibrator_path: calibration_results/
  calibrator_name: platt_lr
  auto_calibrate: false
  force_runner_calibration: false
